image: node:latest

stages:
  - build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/
    - packages/
    - ~/.pnpm-store

build_and_test:
  stage: build
  before_script:
    - curl -L https://unpkg.com/@pnpm/self-installer | node
    - pnpm config set store-dir ~/.pnpm-store
    - pnpm install --frozen-lockfile
    - pnpm recursive install --frozen-lockfile
  script:
    - pnpm build
    - pnpm test

  artifacts:
    paths:

